language: ruby
rvm:
  - 2.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
cache: bundler
bundler_args: --without development

before_install:
  - gem update --system
  - gem --version

before_script:
  - bundle exec github-pages versions

script:
  - JEKYLL_ENV=development bundle exec jekyll build --config _config.yml,_config_test.yml
  - bundle exec htmlproofer ./_site --only-4xx
  - bundle exec github-pages health-check
  - rm -rf ./_site

branches:
  only:
    - master

git:
  depth: 10
