language: ruby
cache: bundler
sudo: false
rvm: 2.4.2

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_script:
  - bundle lock --add-platform x86-mingw32 x86-mswin32
  - bundle install
  - chmod +x ./scripts/cibuild

script: ./scripts/cibuild

branches:
  only:
    - master

git:
  depth: 10
