language: ruby
cache: bundler
sudo: false
rvm: 2.4.2

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_script:
  - bundle install
  - bundle clean --force
  - chmod +x ./scripts/cibuild
script: ./scripts/cibuild

branches:
  only:
    - master

git:
  depth: 10
