language: ruby
rvm:
  - 2.2
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
cache: bundler

script:
  - bundle exec github-pages versions
  - bundle exec github-pages health-check
  - bundle exec jekyll build --config _config.yml,_config_test.yml
  - bundle exec htmlproofer ./_site --only-4xx

branches:
  only:
    - master

git:
  depth: 10
