# Jekyll config file http://jekyllrb.com/docs/configuration/

# Handling reading
exclude:         ["README.md", "LICENSE", "CNAME"]
encoding:        "utf-8"
markdown_ext:    "markdown,mkdown,mkdn,mkd,md"
textile_ext:     "textile"

# Plugins
gems:            ["jekyll-mentions","jemoji","jekyll-redirect-from","jekyll-sitemap"]

# Conversion
markdown:        kramdown
highlighter:     pygments

# Outputting
permalink:        /:year/:month/:title/
relative_permalinks: true
paginate_path:    /page:num/
paginate:         5
timezone:         Asia/Kathmandu
locale:           en_us

# Serving
baseurl:          "" # does not include hostname

# URL of site, include http://, do not include a trailing slash
url:              http://milanaryal.com

# Site settings
title:            Milan Aryal
description:      "One day I will find the words, and they will be simple."
header-img:       "/assets/img/home-bg.jpg"
author:
  name:           Milan Aryal
  url:            https://plus.google.com/MilanAryal
  email:          considermilan@gmail.com
  twitter:        MilanAryal
  googleplus:     MilanAryal
  github:         MilanAryal
  tumblr:         milanaryal
icon:             "/assets/img/m-icon-white-on-blue.png"
ga_trackid:       "UA-42092423-1"

# Custom vars
github:
  repo:           https://github.com/MilanAryal/milanaryal.github.io
