# Permalinks
permalink:        /:year/:month/:title/
relative_permalinks: true

# Plugins
gems:            ["jekyll-mentions","jemoji","jekyll-redirect-from","jekyll-sitemap"]

# Conversion
markdown:         redcarpet
redcarpet:
  extensions:     ["smart","tables","strikethrough","with_toc_data"]
highlighter:      pygments

# Site settings
title:            Milan Aryal
tagline:          "One day I will find the words, and they will be simple."
url:              http://milanaryal.com
paginate:         5
baseurl:          /
author:
  name:           Milan Aryal
  url:            https://twitter.com/MilanAryal
  email:          considermilan@gmail.com
ga_trackid:       UA-41571464-3

# Custom vars
github:
  repo:           https://github.com/MilanAryal/milanaryal.github.io

menu:
  - title:        About
    url:          /about
