# Jekyll config file http://jekyllrb.com/docs/configuration/

# ----------------------------------------------------------------------
# | Site settings                                                      |
# ----------------------------------------------------------------------

name: "Milan Aryal"
description: "Livin' on the edge of web standards."
url: "https://milanaryal.com"
logo:
  path: "/assets/img/m-icon-blue-on-white.png"
  width: 300
  height: 300
image: "/assets/img/home-bg.jpg"
theme_color: "#2196f3"
author:
  name: "Milan Aryal"
  email: "considermilan@gmail.com"
  uri: "https://twitter.com/MilanAryal"
  avatar: "/assets/img/m-icon-white-on-blue.png"
  bio: "I love getting lost in web design, front-end development, and listening music a lot."
  facebook: considermilan
  twitter: MilanAryal
  google_plus: MilanAryal
  instagram: milanaryal
  vine: MilanAryal
  youtube: considermilan
  linkedin: MilanAryal
  pinterest: milanaryal
  tumblr: milanaryal
  github: MilanAryal
  keybase: milanaryal
  street: "Chandragiri 23"
  locality: Kathmandu
  region: Bagmati
  country: Nepal
  postcode: 44600
facebook:
#  app_id: 1234
#  publisher: 1234
  admins: 100001982813077
twitter:
  username: MilanAryal
disqus_shortname: milanaryal
google_cse_id: "000254926668963224856:z4vgwqv7kla"
google_api_key: "AIzaSyB27uh5sPHJ156nRryf1yuJn6fjo_B7qvI"
google_analytics_id: "UA-42092423-1"


# ----------------------------------------------------------------------
# | Build settings                                                     |
# ----------------------------------------------------------------------

encoding: "utf-8"
timezone: Asia/Kathmandu
locale: en_us
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: 1..3
highlighter: rouge
gist:
  noscript: false
permalink: /:year/:title/
paginate_path: /writings/page:num/
paginate: 10
collections:
  docs:
    output: true
    permalink: /docs/:path/
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: "true"
  -
    scope:
      path: ""
      type: "docs"
    values:
      layout: "page"
      comments: "false"
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
include: ["_pages"]
exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - src
  - node_modules
  - package.json
  - Gruntfile.js
  - vendor
  - bower.json
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
