# Site settings
title: Milan Aryal
email: considermilan@gmail.com
description: ""
baseurl: ""
url: "http://milanaryal.com"
twitter_username: MilanAryal
google-plus_username: +MilanAryal
github_username:  MilanAryal
tumblr_username: milanaryal

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5

# prevent jekyll publishing unwanted github files
exclude: ["README.md", "CNAME", "package.json", "node_modules"]

# Site header-img
header-img: /assets/img/header-img.jpg