# Permalinks
permalink:        /:year/:month/:title/
relative_permalinks: true

# Plugins
gems:            ["jekyll-mentions","jemoji","jekyll-redirect-from","jekyll-sitemap"]

# Setup
title:            Milan Aryal
tagline:          The Jekyll Butler
url:              http://milanaryal.com
paginate:         1
baseurl:          /
author:
  name:           Milan Aryal
  url:            https://twitter.com/MilanAryal
  email:          considermilan@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/MilanAryal/milanaryal.github.io
