# Jekyll config file http://jekyllrb.com/docs/configuration/

# Handling reading
exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - key.asc
  - src
  - package.json
  - Gruntfile.js
encoding: "utf-8"

# Plugins
gems:
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

# Conversion
markdown:     kramdown
kramdown:
  toc_levels: 1..3
highlighter:  pygments

# Outputting
permalink:     /:year/:title/
paginate_path: /page:num/
paginate:      5
timezone:      Asia/Kathmandu
locale:        en_us

# URL of site, include http://, do not include a trailing slash
url: "http://milanaryal.com"

# Site settings
name:             Milan Aryal
description:      "Livin' on the edge of web standards."
icon:             "/assets/img/m-icon-white-on-blue.png"
featured_image:   "/assets/img/home-bg.jpg"
theme_color:      "#2196f3"
author:
  name:           Milan Aryal
  email:          "considermilan@gmail.com"
  url:            "https://twitter.com/MilanAryal"
  twitter:        MilanAryal
  google_plus:    MilanAryal
  github:         MilanAryal
  keybase:        milanaryal
  tumblr:         milanaryal
  linkedin:       MilanAryal
  facebook:       considermilan
  fb_id:          100001982813077
  street:         Chandragiri 23
  locality:       Kathmandu
  region:         Bagmati
  country:        Nepal
  postcode:       00977
disqus_shortname: milanaryal

# Google Analytics
# !! Current Tracking ID only for milanaryal.com !!
google_analytics_id: "UA-42092423-1"

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: "true"

# Compress HTML
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
