# Jekyll config file http://jekyllrb.com/docs/configuration/

# build config
markdown: redcarpet
pygments: true
locale: en_US
timezone: Asia/Kathmandu
encoding: UTF-8

# gems (plugins)
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- ArchiveGenerator

# permalink structure, see http://jekyllrb.com/docs/permalinks/
permalink: /:year/:month/:title/

# prevent jekyll publishing unwanted github files
exclude: ['README.md', 'LICENSE', 'CNAME']

# Setup
title: Milan Aryal
description: 'Making the web a better place.'

# URL of site, include http://, do not include a trailing slash
url: http://milanaryal.com

author:
  name: 'Milan Aryal'
  email: 'considermilan@gmail.com'
  url: https://google.com/+MilanAryal

paginate: 5

# Custom vars
icon: /assets/img/icon.png
cover: /assets/img/cover-img.jpg

social:
  - icon: twitter
    url: //twitter.com/MilanAryal
    desc: Follow me on Twitter

  - icon: github
    url: //github.com/MilanAryal
    desc: Fork me on GitHub

  - icon: googleplus-alt
    url: //google.com/+MilanAryal
    desc: Add me on Google+
    
  - icon: tumblr
    url: http://milanaryal.tumblr.com
    desc: Follow me on Tumblr

  - icon: feed
    url: http://milanaryal.com/feed.xml
    desc: Subscribe to my feed

menu:
  - title: Home
    url: /

  - title: About
    url: /about

  - title: Archive
    url: /archive

copyright:
  author: Milan Aryal
  url: http://milanaryal.com
  type_title: MIT licensed
  type_url: //github.com/MilanAryal/milanaryal.github.io/blob/master/LICENSE
