# Jekyll config file http://jekyllrb.com/docs/configuration/

# Handling reading
exclude:               
  -                    README.md
  -                    LICENSE
  -                    CNAME
  -                    Gemfile
encoding:              "utf-8"

# Plugins
gems:                  
  -                    jemoji
  -                    jekyll-mentions
  -                    jekyll-redirect-from
  -                    jekyll-sitemap

# Conversion
markdown:              kramdown
highlighter:           pygments

# Outputting
permalink:             /:year/:title/
relative_permalinks:   true
paginate_path:         /page:num/
paginate:              5
timezone:              Asia/Kathmandu
locale:                en_us

# URL of site, include http://, do not include a trailing slash
url:                   "http://milanaryal.com"

# Site settings
title:                 Milan Aryal
description:           "Livin' on the edge of web standards."
icon:                  "/assets/img/m-icon-white-on-blue.png"
header_image:          "/assets/img/home-bg.jpg"
author:
  name:                Milan Aryal
  url:                 "https://plus.google.com/+MilanAryal"
  email:               "considermilan@gmail.com"
  twitter:             MilanAryal
  googleplus:          MilanAryal
  github:              MilanAryal
  tumblr:              milanaryal
  linkedin:            MilanAryal
  facebook:            considermilan
ga_trackid:            "UA-42092423-1" # Google Analytics - Tracking ID only for milanaryal.com
fb_admins:             100001982813077
disqus_shortname:      milanaryal

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: "true"
