# Jekyll config file http://jekyllrb.com/docs/configuration/

# Handling reading
exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - key.asc
encoding: "utf-8"

# Plugins
gems:
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap

# Conversion
markdown:    kramdown
highlighter: pygments

# Outputting
permalink:           /:year/:title/
relative_permalinks: true
paginate_path:       /page:num/
paginate:            5
timezone:            Asia/Kathmandu
locale:              en_us

# URL of site, include http://, do not include a trailing slash
url: "http://milanaryal.com"

# Site settings
title:            Milan Aryal
description:      "Livin' on the edge of web standards."
icon:             "/assets/img/m-icon-white-on-blue.png"
featured_image:   "/assets/img/home-bg.jpg"
ga_trackid:       "UA-42092423-1" # Google Analytics - Tracking ID only for milanaryal.com
disqus_shortname: milanaryal
author:
  name:           Milan Aryal
  email:          "considermilan@gmail.com"
  twitter:        MilanAryal
  googleplus:     MilanAryal
  github:         MilanAryal
  tumblr:         milanaryal
  linkedin:       MilanAryal
  facebook:       considermilan
  fb_id:          100001982813077
author_address:
  street:         Chandragiri 23
  locality:       Kathmandu
  region:         Bagmati
  country:        Nepal
  postcode:       00977

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: "true"

# Compress HTML
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
