# Jekyll config file http://jekyllrb.com/docs/configuration/

# Handling reading
exclude:               ["README.md","LICENSE","CNAME","Gemfile"]
encoding:              "utf-8"
markdown_ext:          "markdown,mkdown,mkdn,mkd,md"
textile_ext:           "textile"

# Plugins
gems:                  ["jekyll-mentions","jemoji","jekyll-redirect-from","jekyll-sitemap"]

# Conversion
markdown:              kramdown
highlighter:           pygments

# Outputting
permalink:             /:year/:title/
relative_permalinks:   true
paginate_path:         /page:num/
paginate:              5
timezone:              Asia/Kathmandu
locale:                en_us

# Serving
baseurl:               "" # does not include hostname

# URL of site, include http://, do not include a trailing slash
url:                   http://milanaryal.com

# Site settings
title:                 Milan Aryal
description:           "Livin' on the edge of web standards."
icon:                  "/assets/img/m-icon-white-on-blue.png"
header_image:          "/assets/img/home-bg.jpg"
author:
  name:                Milan Aryal
  url:                 https://plus.google.com/MilanAryal
  email:               considermilan@gmail.com
  twitter:             MilanAryal
  googleplus:          MilanAryal
  github:              MilanAryal
  tumblr:              milanaryal
  linkedin:            MilanAryal
  facebook:            considermilan
ga_trackid:            "UA-42092423-1"
fb_admins:             100001982813077
disqus_shortname:      milanaryal

# Custom vars
github:
  repo:                https://github.com/MilanAryal/milanaryal.github.io

# Site content license ( CC BY 3.0 )
content_license:
  type_title:          Some rights reserved
  type_url:            http://creativecommons.org/licenses/by/3.0/

# Site code license ( MIT license )
code_license:
  type_title:          MIT license
  type_url:            https//github.com/MilanAryal/milanaryal.github.io/blob/master/LICENSE
